-- Run this script in the Supabase SQL Editor.
-- Restaurant records can be imported from the existing frontend data afterwards.

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null unique,
  area text not null,
  lat double precision not null,
  lng double precision not null,
  categories text[] not null default '{}',
  price text not null check (price in ('$', '$$', '$$$', '$$$$')),
  rating numeric(2,1) not null check (rating between 0 and 5),
  description text not null default '',
  tags text[] not null default '{}',
  phone text,
  parking_tier text not null default 'unknown'
    check (parking_tier in ('lot', 'street', 'none', 'unknown')),
  parking_sub text,
  photos text[] not null default '{}',
  maps_url text not null,
  hours jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, restaurant_id)
);

alter table public.restaurants enable row level security;
alter table public.favorites enable row level security;

drop policy if exists "Restaurants are publicly readable" on public.restaurants;
drop policy if exists "Authenticated users can add restaurants" on public.restaurants;
drop policy if exists "Authenticated users can edit restaurants" on public.restaurants;
drop policy if exists "Authenticated users can remove restaurants" on public.restaurants;
drop policy if exists "Users can read their own favorites" on public.favorites;
drop policy if exists "Users can add their own favorites" on public.favorites;
drop policy if exists "Users can remove their own favorites" on public.favorites;

-- restaurants is read-only for everyone (anon + logged-in visitors). There is
-- no insert/update/delete policy for the "authenticated" role on purpose:
-- letting any Google-login visitor write or wipe the table would be a data
-- integrity hole. Writes only happen from trusted offline scripts
-- (scripts/import-restaurants.mjs) using the service_role key, which bypasses
-- RLS entirely by Supabase's own design and needs no policy here.
create policy "Restaurants are publicly readable"
  on public.restaurants for select
  using (true);

create policy "Users can read their own favorites"
  on public.favorites for select
  using (auth.uid() = user_id);

create policy "Users can add their own favorites"
  on public.favorites for insert
  with check (auth.uid() = user_id);

create policy "Users can remove their own favorites"
  on public.favorites for delete
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists restaurants_set_updated_at on public.restaurants;
create trigger restaurants_set_updated_at
before update on public.restaurants
for each row execute function public.set_updated_at();
